apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngram-inference
  labels:
    app: ngram-inference
    name: ngram-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngram-inference
  template:
    metadata:
      labels:
        app: ngram-inference
    spec:
      containers:
        - name: ngram-inference-container
          image: sameer7483/project-ngram:latest
          command: ["python3", "infer.py"]
          ports:
            - protocol: TCP
              containerPort: 5000
          imagePullPolicy: Always
