apiVersion: batch/v1
kind: Job
metadata:
  name: ngram-trainer
spec:
  template:
    spec:
      containers:
        - name: ngram-trainer-container
          image: sameer7483/project-ngram:latest
          command: ["python3", "main.py"]
          volumeMounts:
            - name: sa6142-mnist-pv
              mountPath: "/models"
      volumes:
        - name: sa6142-mnist-pv
          persistentVolumeClaim:
            claimName: sa6142-mnist-pvc
      restartPolicy: Never
  backoffLimit: 4
