apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: my-pvc-claim
    labels:
        app: nginx
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 9Gi
    storageClassName: standard-rwo
