apiVersion: v1
kind: Service
metadata:
    name: infer-service
spec:
    type: LoadBalancer
    selector:
        app: score-app
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
